// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Servora-Kit/servora-example/app/master/service/internal/biz"
	"github.com/Servora-Kit/servora-example/app/master/service/internal/data"
	"github.com/Servora-Kit/servora-example/app/master/service/internal/server"
	"github.com/Servora-Kit/servora-example/app/master/service/internal/service"
	"github.com/Servora-Kit/servora-transport/server/tcp/gen/conf"
	"github.com/Servora-Kit/servora/core/bootstrap"
	"github.com/Servora-Kit/servora/core/registry"
	"github.com/Servora-Kit/servora/obs/telemetry"
	"github.com/go-kratos/kratos/v2"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(runtime *bootstrap.Runtime, tcpconfServer *tcpconf.Server) (*kratos.App, func(), error) {
	corev1Bootstrap := runtime.Bootstrap
	corev1Registry := corev1Bootstrap.Registry
	registrar := registry.NewRegistrar(corev1Registry)
	corev1Server := corev1Bootstrap.Server
	trace := corev1Bootstrap.Trace
	metrics := corev1Bootstrap.Metrics
	app := corev1Bootstrap.App
	logger := runtime.Logger
	telemetryMetrics, err := telemetry.NewMetrics(metrics, app, logger)
	if err != nil {
		return nil, nil, err
	}
	auditor := server.ProvideAuditor()
	corev1Data := corev1Bootstrap.Data
	discovery := corev1Bootstrap.Discovery
	registryDiscovery := registry.NewDiscovery(discovery)
	dialer := data.NewWorkerDialer(corev1Data, trace, registryDiscovery, logger)
	workerRepo := data.NewWorkerRepo(dialer, logger)
	masterUsecase := biz.NewMasterUsecase(workerRepo, logger)
	masterService := service.NewMasterService(masterUsecase)
	grpcServer := server.NewGRPCServer(corev1Server, trace, telemetryMetrics, logger, auditor, masterService)
	httpServer := server.NewHTTPServer(corev1Server, trace, telemetryMetrics, logger, auditor, masterService)
	tcpCommandService := service.NewTCPCommandService(masterService)
	tcpServer := server.NewTCPServer(tcpconfServer, logger, tcpCommandService)
	kratosApp := newApp(runtime, registrar, grpcServer, httpServer, tcpServer)
	return kratosApp, func() {
	}, nil
}
