// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Servora-Kit/servora-example/app/master/service/internal/biz"
	"github.com/Servora-Kit/servora-example/app/master/service/internal/data"
	"github.com/Servora-Kit/servora-example/app/master/service/internal/server"
	"github.com/Servora-Kit/servora-example/app/master/service/internal/service"
	"github.com/Servora-Kit/servora-transport/server/tcp/gen/conf"
	"github.com/Servora-Kit/servora/api/gen/go/servora/conf/v1"
	"github.com/Servora-Kit/servora/obs/telemetry"
	"github.com/Servora-Kit/servora/platform/bootstrap"
	"github.com/Servora-Kit/servora/platform/registry"
	"github.com/Servora-Kit/servora/transport/client"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *conf.Server, discovery *conf.Discovery, confRegistry *conf.Registry, confData *conf.Data, app *conf.App, trace *conf.Trace, metrics *conf.Metrics, tcpconfServer *tcpconf.Server, svcIdentity bootstrap.SvcIdentity, logger log.Logger) (*kratos.App, func(), error) {
	registrar := registry.NewRegistrar(confRegistry)
	telemetryMetrics, err := telemetry.NewMetrics(metrics, app, logger)
	if err != nil {
		return nil, nil, err
	}
	registryDiscovery := registry.NewDiscovery(discovery)
	clientClient, err := client.NewDefaultClient(confData, trace, registryDiscovery, logger)
	if err != nil {
		return nil, nil, err
	}
	workerRepo := data.NewWorkerRepo(clientClient, logger)
	masterUsecase := biz.NewMasterUsecase(workerRepo, logger)
	masterService := service.NewMasterService(masterUsecase)
	grpcServer := server.NewGRPCServer(confServer, trace, telemetryMetrics, logger, masterService)
	httpServer := server.NewHTTPServer(confServer, trace, telemetryMetrics, logger, masterService)
	tcpCommandService := service.NewTCPCommandService(masterService)
	tcpServer := server.NewTCPServer(tcpconfServer, logger, tcpCommandService)
	kratosApp := newApp(svcIdentity, logger, registrar, grpcServer, httpServer, tcpServer)
	return kratosApp, func() {
	}, nil
}
