// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Servora-Kit/servora-example/app/master/service/internal/biz"
	"github.com/Servora-Kit/servora-example/app/master/service/internal/data"
	"github.com/Servora-Kit/servora-example/app/master/service/internal/server"
	"github.com/Servora-Kit/servora-example/app/master/service/internal/service"
	tcpconf "github.com/Servora-Kit/servora-transport/server/tcp/gen/conf"
	corev1 "github.com/Servora-Kit/servora/api/gen/go/servora/core/v1"
	"github.com/Servora-Kit/servora/obs/telemetry"
	"github.com/Servora-Kit/servora/core/bootstrap"
	"github.com/Servora-Kit/servora/core/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *corev1.Server, discovery *corev1.Discovery, confRegistry *corev1.Registry, confData *corev1.Data, app *corev1.App, trace *corev1.Trace, metrics *corev1.Metrics, tcpconfServer *tcpconf.Server, svcIdentity bootstrap.SvcIdentity, logger log.Logger) (*kratos.App, func(), error) {
	registrar := registry.NewRegistrar(confRegistry)
	telemetryMetrics, err := telemetry.NewMetrics(metrics, app, logger)
	if err != nil {
		return nil, nil, err
	}
	auditor := server.ProvideAuditor()
	registryDiscovery := registry.NewDiscovery(discovery)
	dialer := data.NewWorkerDialer(confData, trace, registryDiscovery, logger)
	workerRepo := data.NewWorkerRepo(dialer, logger)
	masterUsecase := biz.NewMasterUsecase(workerRepo, logger)
	masterService := service.NewMasterService(masterUsecase)
	grpcServer := server.NewGRPCServer(confServer, trace, telemetryMetrics, logger, auditor, masterService)
	httpServer := server.NewHTTPServer(confServer, trace, telemetryMetrics, logger, auditor, masterService)
	tcpCommandService := service.NewTCPCommandService(masterService)
	tcpServer := server.NewTCPServer(tcpconfServer, logger, tcpCommandService)
	kratosApp := newApp(svcIdentity, logger, registrar, grpcServer, httpServer, tcpServer)
	return kratosApp, func() {
	}, nil
}
