services:
    consul:
        image: consul:1.15.4
        container_name: example_consul
        restart: unless-stopped
        command:
            - agent
            - -server
            - -ui
            - -node=consul-server-1
            - -bootstrap-expect=1
            - -client=0.0.0.0
            - -data-dir=/consul/data
        healthcheck:
            test: ["CMD", "consul", "info"]
            interval: 10s
            timeout: 5s
            retries: 10
        ports:
            - "8500:8500"
            - "8600:8600/udp"
        volumes:
            - example-consul-data:/consul/data
        networks:
            - master-network

volumes:
    example-consul-data:
    master-logs:
    worker-logs:

networks:
    master-network:
