// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ApplicationsColumns holds the columns for the "applications" table.
	ApplicationsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "client_id", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "client_secret_hash", Type: field.TypeString, Size: 255},
		{Name: "name", Type: field.TypeString, Size: 128},
		{Name: "redirect_uris", Type: field.TypeJSON},
		{Name: "scopes", Type: field.TypeJSON},
		{Name: "grant_types", Type: field.TypeJSON},
		{Name: "application_type", Type: field.TypeString, Size: 32, Default: "web"},
		{Name: "access_token_type", Type: field.TypeString, Size: 32, Default: "jwt"},
		{Name: "type", Type: field.TypeString, Size: 32, Default: "web"},
		{Name: "id_token_lifetime", Type: field.TypeInt, Default: 3600},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// ApplicationsTable holds the schema information for the "applications" table.
	ApplicationsTable = &schema.Table{
		Name:       "applications",
		Columns:    ApplicationsColumns,
		PrimaryKey: []*schema.Column{ApplicationsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "username", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 128},
		{Name: "password", Type: field.TypeString, Size: 255},
		{Name: "phone", Type: field.TypeString, Nullable: true, Size: 32},
		{Name: "phone_verified", Type: field.TypeBool, Default: false},
		{Name: "role", Type: field.TypeString, Size: 32, Default: "user"},
		{Name: "status", Type: field.TypeString, Size: 32, Default: "active"},
		{Name: "email_verified", Type: field.TypeBool, Default: false},
		{Name: "email_verified_at", Type: field.TypeTime, Nullable: true},
		{Name: "profile", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ApplicationsTable,
		UsersTable,
	}
)

func init() {
	ApplicationsTable.Annotation = &entsql.Annotation{
		Table: "applications",
	}
	UsersTable.Annotation = &entsql.Annotation{
		Table: "users",
	}
}
