// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Servora-Kit/servora-example/app/worker/service/internal/server"
	"github.com/Servora-Kit/servora-example/app/worker/service/internal/service"
	corev1 "github.com/Servora-Kit/servora/api/gen/go/servora/core/v1"
	"github.com/Servora-Kit/servora/obs/telemetry"
	"github.com/Servora-Kit/servora/core/bootstrap"
	"github.com/Servora-Kit/servora/core/registry"
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(confServer *corev1.Server, confRegistry *corev1.Registry, data *corev1.Data, app *corev1.App, trace *corev1.Trace, metrics *corev1.Metrics, svcIdentity bootstrap.SvcIdentity, logger log.Logger) (*kratos.App, func(), error) {
	registrar := registry.NewRegistrar(confRegistry)
	telemetryMetrics, err := telemetry.NewMetrics(metrics, app, logger)
	if err != nil {
		return nil, nil, err
	}
	auditor := server.ProvideAuditor()
	workerService := service.NewWorkerService(auditor)
	grpcServer := server.NewGRPCServer(confServer, trace, telemetryMetrics, logger, auditor, workerService)
	kratosApp := newApp(svcIdentity, logger, registrar, grpcServer)
	return kratosApp, func() {
	}, nil
}
