// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/Servora-Kit/servora-example/app/worker/service/internal/server"
	"github.com/Servora-Kit/servora-example/app/worker/service/internal/service"
	"github.com/Servora-Kit/servora/core/bootstrap"
	"github.com/Servora-Kit/servora/core/registry"
	"github.com/Servora-Kit/servora/obs/metrics"
	"github.com/go-kratos/kratos/v3"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

func wireApp(runtime *bootstrap.Runtime) (*kratos.App, func(), error) {
	corev1Bootstrap := runtime.Bootstrap
	corev1Registry := corev1Bootstrap.Registry
	registrar := registry.NewRegistrar(corev1Registry)
	corev1Server := corev1Bootstrap.Server
	observability := corev1Bootstrap.Obs
	app := corev1Bootstrap.App
	logger := runtime.Logger
	metricsMetrics, cleanup, err := metrics.New(observability, app, logger)
	if err != nil {
		return nil, nil, err
	}
	auditor := server.ProvideAuditor(logger)
	workerService := service.NewWorkerService(auditor)
	grpcServer := server.NewGRPCServer(corev1Server, observability, metricsMetrics, logger, auditor, workerService)
	kratosApp := newApp(runtime, registrar, grpcServer)
	return kratosApp, func() {
		cleanup()
	}, nil
}
