package main

import (
	"fmt"
	"path"
	"sort"
	"strings"
	"unicode"

	auditv1 "github.com/Servora-Kit/servora/api/gen/go/servora/audit/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		// Build service alias index: serviceName → []fullServiceName across all files.
		// This mirrors the authz plugin logic so operation paths include all full package variants.
		svcAliases := map[string][]string{}
		for _, f := range gen.Files {
			for _, svc := range f.Services {
				name := string(svc.Desc.Name())
				full := string(svc.Desc.FullName())
				svcAliases[name] = append(svcAliases[name], full)
			}
		}

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			processFile(gen, f, svcAliases)
		}
		return nil
	})
}

type ruleEntry struct {
	Operation    string
	EventType    auditv1.AuditEventType
	MutationType auditv1.ResourceMutationType
	TargetType   string
	TargetIDPath string // e.g. "resp.id", "req.id"
	RecordOnError bool
	MethodName   string // for TargetIDFunc naming
}

func processFile(gen *protogen.Plugin, f *protogen.File, svcAliases map[string][]string) {
	var rules []ruleEntry

	for _, svc := range f.Services {
		for _, m := range svc.Methods {
			ext := proto.GetExtension(m.Desc.Options(), auditv1.E_AuditRule)
			if ext == nil {
				continue
			}
			r, ok := ext.(*auditv1.AuditRule)
			if !ok || r == nil || !r.Enabled {
				continue
			}

			methodName := string(m.Desc.Name())
			svcName := string(svc.Desc.Name())

			for _, fullSvc := range svcAliases[svcName] {
				rules = append(rules, ruleEntry{
					Operation:    fmt.Sprintf("/%s/%s", fullSvc, methodName),
					EventType:    r.EventType,
					MutationType: r.MutationType,
					TargetType:   r.TargetType,
					TargetIDPath: r.TargetIdField,
					RecordOnError: r.RecordOnError,
					MethodName:   methodName,
				})
			}
		}
	}

	if len(rules) == 0 {
		return
	}

	sort.Slice(rules, func(i, j int) bool {
		return rules[i].Operation < rules[j].Operation
	})

	dir := path.Dir(f.GeneratedFilenamePrefix)
	g := gen.NewGeneratedFile(path.Join(dir, "audit_rules.gen.go"), f.GoImportPath)
	generateFile(g, f.GoPackageName, rules)
}

func generateFile(g *protogen.GeneratedFile, pkgName protogen.GoPackageName, rules []ruleEntry) {
	auditPkg := protogen.GoImportPath("github.com/Servora-Kit/servora/pkg/audit")
	auditv1Pkg := protogen.GoImportPath("github.com/Servora-Kit/servora/api/gen/go/servora/audit/v1")

	g.P("// Code generated by protoc-gen-servora-audit. DO NOT EDIT.")
	g.P()
	g.P("package ", pkgName)
	g.P()

	auditRule := g.QualifiedGoIdent(protogen.GoIdent{GoName: "Rule", GoImportPath: auditPkg})

	// Emit target ID extractor functions for rules with target_id_field set.
	for _, r := range rules {
		if r.TargetIDPath == "" {
			continue
		}
		funcName := extractFuncName(r.MethodName)
		prefix, field := parseTargetIDPath(r.TargetIDPath)
		goField := goGetter(field)

		g.P(fmt.Sprintf("func %s(req, resp any) string {", funcName))
		if prefix == "resp" {
			g.P(fmt.Sprintf("	if r, ok := resp.(interface{ Get%s() string }); ok && r != nil {", goField))
			g.P(fmt.Sprintf("		return r.Get%s()", goField))
		} else {
			g.P(fmt.Sprintf("	if r, ok := req.(interface{ Get%s() string }); ok && r != nil {", goField))
			g.P(fmt.Sprintf("		return r.Get%s()", goField))
		}
		g.P("	}")
		g.P("	return \"\"")
		g.P("}")
		g.P()
	}

	// Emit backing var.
	g.P("// _auditRules is the immutable backing store for AuditRules.")
	g.P("var _auditRules = map[string]", auditRule, "{")
	for _, r := range rules {
		g.P(fmt.Sprintf("	%q: {", r.Operation))

		// EventType
		if r.EventType != auditv1.AuditEventType_AUDIT_EVENT_TYPE_UNSPECIFIED {
			evtIdent := g.QualifiedGoIdent(protogen.GoIdent{
				GoName:       "EventType" + auditEventTypeSuffix(r.EventType),
				GoImportPath: auditPkg,
			})
			g.P("		EventType: ", evtIdent, ",")
		}

		// MutationType
		if r.MutationType != auditv1.ResourceMutationType_RESOURCE_MUTATION_TYPE_UNSPECIFIED {
			mutIdent := g.QualifiedGoIdent(protogen.GoIdent{
				GoName:       "ResourceMutation" + mutationTypeSuffix(r.MutationType),
				GoImportPath: auditPkg,
			})
			_ = mutIdent // suppress unused import warning — it's used below
			g.P("		MutationType: ", mutIdent, ",")
		}

		if r.TargetType != "" {
			g.P(fmt.Sprintf("		TargetType: %q,", r.TargetType))
		}

		if r.RecordOnError {
			g.P("		RecordOnError: true,")
		}

		if r.TargetIDPath != "" {
			funcName := extractFuncName(r.MethodName)
			g.P(fmt.Sprintf("		TargetIDFunc: %s,", funcName))
		}

		g.P("	},")
	}
	g.P("}")
	g.P()

	// Emit copy-returning func.
	_ = auditv1Pkg // imported for proto enum resolution
	g.P("// AuditRules returns a copy of the audit rules for this package.")
	g.P("// Each call returns an independent map; callers may not modify the returned map.")
	g.P("func AuditRules() map[string]", auditRule, " {")
	g.P("	m := make(map[string]", auditRule, ", len(_auditRules))")
	g.P("	for k, v := range _auditRules {")
	g.P("		m[k] = v")
	g.P("	}")
	g.P("	return m")
	g.P("}")
}

// extractFuncName returns the TargetIDFunc name for a given method name.
func extractFuncName(methodName string) string {
	return fmt.Sprintf("_extract%sTargetID", methodName)
}

// parseTargetIDPath splits "req.field.sub" into ("req", "field.sub").
func parseTargetIDPath(path string) (prefix, rest string) {
	parts := strings.SplitN(path, ".", 2)
	if len(parts) != 2 {
		return "req", path
	}
	return parts[0], parts[1]
}

// goGetter converts a snake_case field path to a PascalCase Go getter name.
// E.g. "user_id" → "UserId", "id" → "Id".
func goGetter(field string) string {
	parts := strings.Split(field, "_")
	var b strings.Builder
	for _, p := range parts {
		if len(p) == 0 {
			continue
		}
		runes := []rune(p)
		runes[0] = unicode.ToUpper(runes[0])
		b.WriteString(string(runes))
	}
	return b.String()
}

// auditEventTypeSuffix maps proto enum to Go audit.EventType* suffix.
func auditEventTypeSuffix(t auditv1.AuditEventType) string {
	switch t {
	case auditv1.AuditEventType_AUDIT_EVENT_TYPE_RESOURCE_MUTATION:
		return "ResourceMutation"
	case auditv1.AuditEventType_AUDIT_EVENT_TYPE_AUTHZ_DECISION:
		return "AuthzDecision"
	case auditv1.AuditEventType_AUDIT_EVENT_TYPE_AUTHN_RESULT:
		return "AuthnResult"
	case auditv1.AuditEventType_AUDIT_EVENT_TYPE_TUPLE_CHANGED:
		return "TupleChanged"
	default:
		return "ResourceMutation"
	}
}

// mutationTypeSuffix maps proto enum to Go audit.ResourceMutation* suffix.
func mutationTypeSuffix(t auditv1.ResourceMutationType) string {
	switch t {
	case auditv1.ResourceMutationType_RESOURCE_MUTATION_TYPE_CREATE:
		return "Create"
	case auditv1.ResourceMutationType_RESOURCE_MUTATION_TYPE_UPDATE:
		return "Update"
	case auditv1.ResourceMutationType_RESOURCE_MUTATION_TYPE_DELETE:
		return "Delete"
	default:
		return "Update"
	}
}
