package main

import (
	"fmt"
	"path"
	"sort"

	authzpb "github.com/Servora-Kit/servora/api/gen/go/authz/service/v1"
	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/pluginpb"
)

func main() {
	protogen.Options{}.Run(func(gen *protogen.Plugin) error {
		gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)

		var rules []ruleEntry
		var targetFile *protogen.File

		for _, f := range gen.Files {
			if !f.Generate {
				continue
			}
			for _, svc := range f.Services {
				for _, m := range svc.Methods {
					ext := proto.GetExtension(m.Desc.Options(), authzpb.E_Rule)
					if ext == nil {
						continue
					}
					r, ok := ext.(*authzpb.AuthzRule)
					if !ok || r == nil || r.Mode == authzpb.AuthzMode_AUTHZ_MODE_UNSPECIFIED {
						continue
					}
					if targetFile == nil {
						targetFile = f
					}
					operation := fmt.Sprintf("/%s/%s", svc.Desc.FullName(), m.Desc.Name())
					rules = append(rules, ruleEntry{
						Operation:  operation,
						Mode:       r.Mode,
						Relation:   r.Relation,
						ObjectType: r.ObjectType,
						IDField:    r.IdField,
					})
				}
			}
		}

		if len(rules) == 0 || targetFile == nil {
			return nil
		}

		sort.Slice(rules, func(i, j int) bool {
			return rules[i].Operation < rules[j].Operation
		})

		dir := path.Dir(targetFile.GeneratedFilenamePrefix)
		g := gen.NewGeneratedFile(path.Join(dir, "authz_rules.gen.go"), targetFile.GoImportPath)
		generateFile(g, targetFile.GoPackageName, rules)
		return nil
	})
}

type ruleEntry struct {
	Operation  string
	Mode       authzpb.AuthzMode
	Relation   authzpb.Relation
	ObjectType authzpb.ObjectType
	IDField    string
}

func generateFile(g *protogen.GeneratedFile, pkgName protogen.GoPackageName, rules []ruleEntry) {
	authzPkg := protogen.GoImportPath("github.com/Servora-Kit/servora/api/gen/go/authz/service/v1")

	g.P("// Code generated by protoc-gen-servora-authz. DO NOT EDIT.")
	g.P()
	g.P("package ", pkgName)
	g.P()

	authzMode := g.QualifiedGoIdent(protogen.GoIdent{GoName: "AuthzMode", GoImportPath: authzPkg})
	relation := g.QualifiedGoIdent(protogen.GoIdent{GoName: "Relation", GoImportPath: authzPkg})
	objectType := g.QualifiedGoIdent(protogen.GoIdent{GoName: "ObjectType", GoImportPath: authzPkg})

	g.P("// AuthzRuleEntry describes the authorization requirement for a single RPC operation.")
	g.P("type AuthzRuleEntry struct {")
	g.P("	Mode       ", authzMode)
	g.P("	Relation   ", relation)
	g.P("	ObjectType ", objectType)
	g.P("	IDField    string")
	g.P("}")
	g.P()

	g.P("// AuthzRules maps each annotated RPC operation to its authorization rule.")
	g.P("var AuthzRules = map[string]AuthzRuleEntry{")
	for _, r := range rules {
		modeIdent := g.QualifiedGoIdent(protogen.GoIdent{
			GoName:       "AuthzMode_" + r.Mode.String(),
			GoImportPath: authzPkg,
		})
		g.P(fmt.Sprintf("	%q: {", r.Operation))
		g.P("		Mode: ", modeIdent, ",")

		if r.Relation != authzpb.Relation_RELATION_UNSPECIFIED {
			relIdent := g.QualifiedGoIdent(protogen.GoIdent{
				GoName:       "Relation_" + r.Relation.String(),
				GoImportPath: authzPkg,
			})
			g.P("		Relation: ", relIdent, ",")
		}
		if r.ObjectType != authzpb.ObjectType_OBJECT_TYPE_UNSPECIFIED {
			otIdent := g.QualifiedGoIdent(protogen.GoIdent{
				GoName:       "ObjectType_" + r.ObjectType.String(),
				GoImportPath: authzPkg,
			})
			g.P("		ObjectType: ", otIdent, ",")
		}
		if r.IDField != "" {
			g.P(fmt.Sprintf("		IDField: %q,", r.IDField))
		}
		g.P("	},")
	}
	g.P("}")
}
